[package]
name = "eigentrust-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
dotenv = "0.15.0"
env_logger = "0.10.0"
ethers = "2.0.8"
log = "0.4.19"
reqwest = "0.11.18"
tokio = "1.18"

eigen-trust-client = { path = "../client" }
